### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by henriquecustodia** [help-me-mom/ng-mocks#8887]
I've noticed that Signal Inputs are just treated as Decorator Input. 

> ng-mocks@14.12.2

I have the following component: 
```ts 
@Component({
  selector: 'app-list-item',
  standalone: true,
  templateUrl: './list-item.component.html',
  styleUrl: './list-item.component.scss',
})
export class ListItemComponent { 
  task = input.required<Task>();
}
```

I mock the component using MockComponent function: 

```ts
 await TestBed.configureTestingModule({
      imports: [ListComponent],
      providers: [
        {
          provide: TasksService,
          useValue: tasksServiceStub,
        },
      ],
    })
      .overrideComponent(ListComponent, {
        remove: {
          imports: [ListItemComponent],
        },
        add: {
          imports: [MockComponent(ListItemComponent)], // I mock here
        },
      })
      .compileComponents();
```

And my test try to access the Singal Input from `ListItemComponent` to assert its value: 

```ts
 expect((<ListItemComponent>item.componentInstance).task()).toEqual(completedTasksStub[index]);
```

But the test breaks because the `task` property (it's a Signal Input) is not a function.

The complete error: 
`TypeError: completedItemDebugEl.componentInstance.task is not a function` 

Logging the `<ListItemComponent>item.componentInstance).task` in the test, I see that it's a property

`task: { id: '1', name: 'Buy milk', completed: true }`

Working with Signal Inputs, we need to test it as a Signal and not as a property as it was with Decorator Inputs. 

Any news about that @satanTime? 

Thank for your amazing work btw

**Comment by gvlekke** [comment]
any news if this will be picked up?

**Comment by teowgh** [comment]
Anyone working on it?

**Comment by solovevserg** [comment]
I created a mapped type as a temporary workaround to handle this issue:

```ts
export type WithSignalsUnwrapped<TComponent extends object> = {
    [P in keyof TComponent]: TComponent[P] extends Signal<infer T> ? T : TComponent[P];
};
```

It doesn't cast inputs to signals in a mocked component, but aligns types with the actual mock behaviour. In your case it can be used like this:

```ts
 expect(
    (<WithSignalsUnwrapped<ListItemComponent>>item.componentInstance).task()
).toEqual(completedTasksStub[index]);
```

---

P.S. I believe the issue's auhor initial request requires discussion.

> Working with Signal Inputs, we need to test it as a Signal and not as a property as it was with Decorator Inputs.

`input()` vs `@Input` is a child component implementation detail. From the parent's perspective, the contract (component interface) hasn't changed. I believe the child's input type shouldn't affect parent component tests. Migration to signals should remain transparent to component consumers, including test code. Coupling a mock's behaviour to internal implementation details leads to unexpected test failures during migration to signals and is generally considered a bad practice.

**Comment by derWebdesigner** [comment]
Are there any updates about this? I actually thought that input() is replacing @Input in a modern Angular app, but when I replace @Input where an entity is passed, I always get "this.entity is not a function", no matter where I place it (constructor, ngOnInit, effect). Or am I totally misunderstanding what input() should be?

**Comment by sam-warren-finnair2** [comment]
I agree with the author of this post that this behavior is quite unintuitive. For example when you pass an observable as an input to a component, that observable remains as the type it was passed in as (an observable). By changing the input signal to be the direct value this is not aligning with how a developer would expect it to function in my opinion.

**Comment by derWebdesigner** [comment]
**Here is what I learned and what's hopefully helpful to others:** The issue with “entity is not a function” happens because of how Ionic sends data to the modal. The issue should be resolved by migrating to a standalone app and adding useSetInputAPI: true to the main.ts file. At least for me, this fixed this weird issue.

Example main.ts

```
bootstrapApplication(AppComponent, {
  providers: [
    provideExperimentalZonelessChangeDetection(),
    provideIonicAngular({ useSetInputAPI: true }),
  ],
});
```

**Comment by satanTime** [comment]
[v14.16.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.16.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
